//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TodoListUCBL.EntityFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tache
    {
        public Tache()
        {
            this.Categories = new HashSet<Category>();
        }
    
        public int Id { get; set; }
        public string Nom { get; set; }
        public System.DateTime Debut { get; set; }
        public System.DateTime Fin { get; set; }
        public string Detail { get; set; }
    
        public virtual Etat Etat { get; set; }
        public virtual Utilisateur Utilisateur { get; set; }
        public virtual ICollection<Category> Categories { get; set; }
    }
}
